### PR TITLE
Create pull_request_template

### PR DESCRIPTION
**Pull request by jbreit88**
Everyone please take a look at this pull request template. Leave comments about stuff to add and where.

This is the FE PR template. If you think of anything that needs to be specific to the FE, please comment that. Likewise, if you think of anything that should be specific to the BE PR template, please comment that here as well so I can add it when I make that.

Suggestions for possible additions:
- gifs/images if you'd like to use them
- sections about how we are feeling (about ourselves, about our code, in general, etc)

### CODE REVIEW

**Comment by echon006** [comment]
Maybe a section to note the main purpose of the PR 
as well as a checklist? 

## Checklist

Make sure all are checked before submitting a Pull Request.
- [ ] All test are passing
- [ ] No unused code
- [ ] Documentation of what was added/fixed

**Comment by Malllll12** [comment]
A check about deploying to Heroku sandboxes would be a nice reminder.

**Review by Sierra-T-9598 — APPROVED** [review]
Looks good to me!

**Comment by jbreit88** [comment]
Great suggestions Eric and Mal. 
@echon006 I added your suggestions to the checklist at the bottom of the PR.
@Malllll12 I added a checkbox to the final checklist about double checking deployment to Heroku through a test remote.

**Review by devin-p-lay — APPROVED** [review]
reviewed in person with Brad(the one whom created it) - everything looks great! nice amendments by the team

**Review by Malllll12 — APPROVED** [review]

**Review by echon006 — APPROVED** [review]
looks good, glad my feedback was useful!

**Pull request merged**
